[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
opt-level = 3
lto = true

[profile.dev]
debug = true
opt-level = 1

[profile.bench]
debug = true
opt-level = 3

[dependencies]
